const LEAGUE_ID="1327325072385409024",API="https://api.sleeper.app/v1",MARKET_URL="https://www.dynastydealer.com/api/player-values",CACHE=86400000,HISTORY_MAX=8;
const S={tab:"overview",users:[],rosters:[],drafts:[],picks:[],trades:[],players:{},market:{},seasons:[],league:null};
const $=s=>document.querySelector(s),esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),fmt=x=>x==null?"—":Number(x).toLocaleString();
const grade=s=>s>=93?"A+":s>=88?"A":s>=83?"A-":s>=78?"B+":s>=72?"B":s>=66?"B-":s>=60?"C+":s>=54?"C":s>=48?"C-":s>=40?"D":"F";
async function get(u){const r=await fetch(u);if(!r.ok)throw Error(r.status);return r.json()}
async function cache(k,u){try{let x=JSON.parse(localStorage.getItem(k)||"null");if(x&&Date.now()-x.t<CACHE)return x.d}catch{}let d=await get(u);try{localStorage.setItem(k,JSON.stringify({t:Date.now(),d}))}catch{}return d}
function player(id){return S.players[String(id)]||{}}function market(id){return S.market[String(id)]||{}}function value(id){return Number(market(id).current_value??market(id).value??0)}
function age(id){let a=Number(market(id).age??player(id).age);return a>0?a:null}function pos(id){return String(market(id).position||player(id).position||"").toUpperCase()}
function user(id){let x=S.users.find(u=>String(u.user_id)===String(id));return x?.display_name||x?.username||`User ${id}`}
function roster(id){return S.rosters.find(r=>Number(r.roster_id)===Number(id))}
function rosterValue(r){return(r?.players||[]).reduce((n,id)=>n+value(id),0)}
function direction(r){let a=(r?.players||[]).map(age).filter(Boolean),avg=a.length?a.reduce((x,y)=>x+y,0)/a.length:26,rv=rosterValue(r),rank=Number(r?.settings?.rank||99);return(rank<=4&&rv>25000)||(avg<25.5&&rv>22000)?"contender":(rank>=9||avg>=27.2?"rebuild":"middle")}
function pickValue(p){let b={1:5000,2:2800,3:1500,4:800}[Number(p.round)]||500,y=Math.max(0,(Number(p.season)||2026)-2026);return Math.round(b*Math.pow(.82,y))}
function pickName(p){return`${p.season} ${({1:"1st",2:"2nd",3:"3rd",4:"4th"})[Number(p.round)]||p.round+"th"}`}
function sides(tx){let s={};for(let r of tx.roster_ids||[])s[r]={received:[],sent:[],valueReceived:0,valueSent:0};for(let[pid,r]of Object.entries(tx.adds||{}))if(s[r])s[r].received.push({name:player(pid).full_name||market(pid).name||pid,type:"player",id:pid,value:value(pid),age:age(pid),pos:pos(pid)});for(let[pid,r]of Object.entries(tx.drops||{}))if(s[r])s[r].sent.push({name:player(pid).full_name||market(pid).name||pid,type:"player",id:pid,value:value(pid),age:age(pid),pos:pos(pid)});for(let p of tx.draft_picks||[]){let a={name:pickName(p),type:"pick",value:pickValue(p),pos:"PICK"};if(p.owner_id!=null&&s[p.owner_id])s[p.owner_id].received.push(a);if(p.previous_owner_id!=null&&s[p.previous_owner_id])s[p.previous_owner_id].sent.push(a)}for(let x of Object.values(s)){x.valueReceived=x.received.reduce((n,a)=>n+a.value,0);x.valueSent=x.sent.reduce((n,a)=>n+a.value,0)}return s}
function score(r,s){let rec=s.valueReceived||1,sent=s.valueSent||1,edge=Math.max(-18,Math.min(18,(rec-sent)/Math.max(rec,sent)*28)),need=0,dir=direction(r),pv={QB:0,RB:0,WR:0,TE:0};for(let id of r?.players||[]){let p=pos(id);if(pv[p]!=null)pv[p]+=value(id)}let rp={QB:0,RB:0,WR:0,TE:0};s.received.forEach(a=>{if(rp[a.pos]!=null)rp[a.pos]+=a.value});let total=Object.values(pv).reduce((a,b)=>a+b,0)||1;for(let p of Object.keys(pv)){let sh=pv[p]/total;if(sh<.16&&rp[p]>0)need+=5;else if(sh>.38&&rp[p]>pv[p]*.2)need-=3}let recp=s.received.filter(a=>a.type==="player"&&a.age),adj=0;if(dir==="rebuild"){let y=recp.filter(a=>a.age<=24).reduce((n,a)=>n+a.value,0),o=recp.filter(a=>a.age>=28).reduce((n,a)=>n+a.value,0);adj=Math.max(-6,Math.min(8,(y-o)/rec*14))}else if(dir==="contender"){let w=recp.filter(a=>a.age>=25&&a.age<=29).reduce((n,a)=>n+a.value,0),f=recp.filter(a=>a.age<=23).reduce((n,a)=>n+a.value,0);adj=Math.max(-6,Math.min(8,(w-f)/rec*12))}let sc=Math.max(0,Math.min(100,70+edge+need+adj+(rec>sent?2:0)));return{sc,grade:grade(sc),edge,need,adj,dir}}
function assetHTML(a){return a.length?a.map(x=>`<div class="asset"><span>${esc(x.name)} ${x.pos&&x.pos!=="PICK"?`<small>${x.pos}</small>`:""}</span><b>${fmt(x.value)}</b></div>`).join(""):"<span class=muted>None</span>"}
async function loadSeason(id){if(!id||S.seasons.some(x=>x.id===id))return null;let l;try{l=await get(`${API}/league/${id}`)}catch{return null}let users=[],rosters=[];try{users=await get(`${API}/league/${id}/users`)}catch{}try{rosters=await get(`${API}/league/${id}/rosters`)}catch{}let s={id,season:l.season||"Unknown",name:l.name||"League",previous:l.previous_league_id,users,rosters,trades:0};S.seasons.push(s);let seen=new Set;for(let w=1;w<=18;w++)try{for(let t of await get(`${API}/league/${id}/transactions/${w}`)||[])if(t.type==="trade"&&!seen.has(t.transaction_id)){seen.add(t.transaction_id);t._season=s;S.trades.push(t);s.trades++}}catch{}return s}
function histUser(s,rid){let r=s.rosters.find(x=>Number(x.roster_id)===Number(rid)),u=s.users.find(x=>String(x.user_id)===String(r?.owner_id));return u?.display_name||u?.username||`Roster ${rid}`}
function renderTrades(){if(!S.trades.length)return`<div class=panel>No trades found.</div>`;return`<div class=panel><h2>Trade Grades — V2.2</h2><div class=notice><b>Each manager now receives an individual grade.</b> Grades use current Dynasty Dealer values plus roster need, direction, age and package size. Historical trades are identified by their original season, but values are not falsely frozen to the trade date.</div>${S.trades.sort((a,b)=>(b.created||0)-(a.created||0)).map(t=>{let s=t._season,z=sides(t),e=Object.entries(z);if(e.length<2)return"";return`<div class=trade><div><b>${t.created?new Date(t.created).toLocaleDateString():"Unknown date"}</b> <span class=pill>${esc(s.season)} season</span></div><div class=sides>${e.map(([rid,x])=>{let r=s.rosters.find(q=>Number(q.roster_id)===Number(rid))||roster(rid),c=score(r,x);return`<div class=side><h3>${esc(s?histUser(s,rid):user(r?.owner_id))}<span class=grade>${c.grade}</span></h3><div class=muted>${c.dir} • ${Math.round(c.sc)}/100</div><div class=label>Received</div>${assetHTML(x.received)}<div class=label>Sent</div>${assetHTML(x.sent)}<div class=bar><i style="width:${c.sc}%"></i></div><div class=muted>Market ${c.edge>=0?"+":""}${c.edge.toFixed(1)} • Need ${c.need>=0?"+":""}${c.need.toFixed(1)} • Direction ${c.adj>=0?"+":""}${c.adj.toFixed(1)}</div></div>`}).join("")}</div></div>`}).join("")}</div>`}
function render(){let html;if(S.tab==="trades")html=renderTrades();else if(S.tab==="history")html=`<div class=panel><h2>League History</h2>${S.seasons.map((s,i)=>`<p><b>${esc(s.season)}</b>${i===0?" — Current":""} • ${s.trades} trades • previous league: ${esc(s.previous||"None")}</p>`).join("")}</div>`;else if(S.tab==="grades")html=`<div class=panel><h2>V2.2 Grading Model</h2><p>Market edge, roster need, team direction, age profile and package size.</p><p>Every trade displays an individual manager grade. Historical season traversal follows Sleeper's previous_league_id chain.</p></div>`;else if(S.tab==="overview")html=`<div class=grid><div class=card><h3>Teams</h3><div class=metric>${S.rosters.length}</div></div><div class=card><h3>Trades</h3><div class=metric>${S.trades.length}</div></div><div class=card><h3>Seasons</h3><div class=metric>${S.seasons.length}</div></div><div class=card><h3>Market Assets</h3><div class=metric>${Object.keys(S.market).length}</div></div></div>`;else html=`<div class=panel><h2>${S.tab[0].toUpperCase()+S.tab.slice(1)}</h2><p class=muted>Data synced from Sleeper.</p></div>`;$("#app").innerHTML=html;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===S.tab))}
async function sync(){let st=$("#status");st.textContent="Syncing current and historical league data…";try{S.league=await get(`${API}/league/${LEAGUE_ID}`);S.users=await get(`${API}/league/${LEAGUE_ID}/users`);S.rosters=await get(`${API}/league/${LEAGUE_ID}/rosters`);S.drafts=await get(`${API}/league/${LEAGUE_ID}/drafts`);S.players=await cache("dhq_players",`${API}/players/nfl`);try{let raw=await cache("dhq_market",MARKET_URL);for(let x of(Array.isArray(raw)?raw:(raw.players||[])))if(x.sleeper_id!=null)S.market[x.sleeper_id]=x}catch{}S.trades=[];S.seasons=[];let id=LEAGUE_ID;for(let i=0;i<HISTORY_MAX&&id;i++){let s=await loadSeason(id);if(!s)break;id=s.previous}st.textContent=`Synced • ${S.trades.length} trades across ${S.seasons.length} seasons`;render()}catch(e){st.textContent=`Sync failed: ${e.message}`}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()});$("#sync").onclick=sync;render();sync();